# Generated by Django 2.1.7 on 2019-03-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Currency',
                'db_table': 'currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=12, max_digits=24)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='currency_exchange.Currency')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchange.Provider')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='currency_exchange.Currency')),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'db_table': 'currency_exchange_rate',
                'verbose_name_plural': 'Currency Exchange Rates',
            },
        ),
    ]
