# Generated by Django 2.1.7 on 2019-03-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0006_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
