# Generated by Django 2.1.7 on 2019-03-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0008_auto_20190323_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='YYY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchange.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchange.Users')),
            ],
            options={
                'verbose_name': 'YYY',
                'verbose_name_plural': 'YYYs',
                'db_table': 'YYY',
            },
        ),
    ]
