# Generated by Django 2.1.7 on 2019-03-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0009_yyy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yyy',
            old_name='proj',
            new_name='project',
        ),
    ]
