# Generated by Django 2.1.7 on 2019-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0010_auto_20190324_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='yyy',
            name='task_name',
            field=models.CharField(default='---', max_length=200),
        ),
    ]
