# Generated by Django 2.1.7 on 2019-03-24 10:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0014_auto_20190324_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=200)),
                ('task_description', models.CharField(default='', max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 12, 0, 48, 376537))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2019, 3, 24, 12, 0, 48, 376537))),
                ('hours', models.DecimalField(decimal_places=12, max_digits=24)),
                ('status', models.CharField(default='in progress', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchange.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchange.Users')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
            },
        ),
    ]
