# Generated by Django 2.1.7 on 2019-03-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0016_auto_20190324_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimation_hours',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_exchange.TaskStatus'),
        ),
    ]
